version: '3.5'

networks: 
    localdev:
        name: localdev

services:
    main-api:
        build: Hahn.ApplicatonProcess.February2021.API/
        restart: always
        ports:
            - "5005:80"
        networks: 
            - localdev